version: '3'

services:
  api:
    container_name: api
    build:
        context: ./api/
        dockerfile: Dockerfile
    image: fastapi:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: ps-mysql
    image: mysql:5.7
    restart: unless-stopped
    volumes:
       - ./db/data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: ps
       MYSQL_USER: ps
       MYSQL_PASSWORD: ps
    ports:
      - "3306:3306"
