version: '3'

services:
  db:
    container_name: ps-mysql
    image: mysql:5.7
    volumes:
       - ./data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: ps
       MYSQL_USER: ps
       MYSQL_PASSWORD: ps
    ports:
      - "3306:3306"

